# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------


from knack.help_files import helps

helps[
    "git"
] = """
type: group
short-summary: Use GPT enchanced git commands.
"""

helps[
    "git commit"
] = """
type: command
short-summary: Run git commit with a commit message generated by GPT.
"""
