on: [pull_request_target]

jobs:
  add_pr_comment:
    permissions: write-all
    runs-on: ubuntu-latest
    name: OpenAI PR Comment
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - run: |
          echo "value=`GITHUB_VARS ${{ github.repository }}`" >> $GITHUB_OUTPUT
          echo ${{ github.repository_owner }}
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
